service: forklift
frameworkVersion: "=1.8.0"

provider:
  name: aws
  runtime: nodejs4.3
  profile: ${opt:profile}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:ListStreams
        - dynamodb:GetShardIterator
        - dynamodb:GetRecords
        - dynamodb:DescribeStream
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/*"

functions:
  createMessage:
    handler: src/message/handler.createMessage
    events:
      - http:
          path: topics/{topicId}/messages
          method: post
          cors: true
  createTopic:
    handler: src/topic/handler.createTopic
    events:
      - http:
          path: topics
          method: post
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:us-east-1:651189268295:userpool/us-east-1_wLNFEdP92

resources:
  Resources:
    MessagesTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        TableName: "messages"
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_IMAGE
    TopicsTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        TableName: "topics"
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

plugins:
  - serverless-offline
